name : demo
on : 
  workflow_dispatch :
    inputs :
      envdep :
        description : 'environnement de déploiment'
        required : true
        default : 'dev'
jobs :
  deploy-env : 
    runs-on : ubuntu-latest
    steps :
      - name : demarrage workflow
        run : echo 'bien dans le main'
        if : ${{github.refs == 'refs/head/main'}}
