name : demo
on : 
  workflow_dispatch :
    inputs :
      envdep :
        description : 'environnement de déploiment'
        required : true
        default : 'dev'
jobs :
  deploy-env : 
    runs-on : ubuntu-latest
    steps :
      - name : demarrage workflow
        run : echo 'démarrage workflow sur ${{github.ref}} '
      - name : recuperation code
        run : echo 'récupération de code'
        if: ${{github.ref == 'refs/heads/main'}}
