name : demo
on : 
  workflow_dispatch :
    inputs :
      envdep :
        description : 'environnement de déploiment'
        required : true
        default : 'dev'
jobs :
  deploy-env : 
    runs-on : ubuntu-latest
    steps :
      - name : demarrage workflow
        run : echo 'démarrage workflow sur ${{github.ref}} '
      - name : Checkout
        if: ${{github.ref == 'refs/heads/main'}}
        uses: actions/checkout@v4.1.1
      - name : déploiement production
        run : echo "déploiement en production"
        if : github.event.inputs.envdep == 'prod'
